### ISSUE TITLE
Round edge shader data?

### ISSUE THREAD

**Issue by sttng** [Polymaker/ldd-modder#2]
Did you found out all the details of the Round edge shader data of the .g files ?

**Comment by Polymaker** [comment]
Yes I have!
It has been a while since I worked on this project so I don't remember everything but the gist of it is that the "round edge data" is actually a set of UV maps used to render the edges.

Basically, there is six UV map used with a texture with a 1px border at the top (but IIRC the image is flipped vertically when passed to the shader). 

The UV maps are processed as three pairs for each triangle. The resulting textures of a pair are merged either by "union" or "intersection". 
An intersection is achieved by having the X value negative (for each index of a triangle) of the second coord in a pair. The values are often offseted by 100 to allow having negative values when the X value would be zero.
Intersections are used to accomplish acute angles or corners that meets inside a triangle.

Feel free to ask me anything if you need more in-depth info.

**Comment by Polymaker** [comment]
You may be interested in my documentation of the G file format.
It has a section about the round edge data but only explains how the data is packed for the moment.
Check-it out [here](https://github.com/Polymaker/ldd-modder/blob/v2/Documentation/G%20(mesh)%20file%20structure.md)

**Comment by sttng** [comment]
Thank you so much for the details. I’m not sure if you are aware of but there has been a fair amount of progress in adding new parts to LDD in the recent days. 

https://www.eurobricks.com/forum/index.php?/forums/topic/177795-key-topic-ldd-new-parts/

https://www.eurobricks.com/forum/index.php?/forums/topic/170286-custom-ldd-bricks-and-fixes/

Wondering if you would like to continue your work with a more complete converter?
